# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: nameko-plus
theme:
  name: material
  palette:
    scheme: default
    primary: deep orange
    accent: indigo
