# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: nameko-plus
repo_url: https://gitea.bearcatlog.com/BryantStudio
repo_name: BryantStudio/nameko-plus
theme:
  name: material
  language: zh
  # logo: assets/logo.png
  icon:
    logo: simple/materialdesign
    repo: simple/gitea
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: 切至暗黑模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: 切至光亮模式
extra:
  alternate:
    - name: 简体中文
      link: https://doc.bearcatlog.com/
      lang: zh
    - name: English
      link: https://apiflask.com/
      lang: en